version: "1"

services:
  postgres:
    image: bitnami/postgresql:15
    restart: no
    hostname: postgres
    container_name: diplomski_rad
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=satovi
      - POSTGRESQL_DATABASE=watchSM
      - POSTGRESQL_WAL_LEVEL=logical
    ports:
      - "5432:5432"
